<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>自定义Promise</title>
    <script src="../js/promise.js"></script>
</head>
<body>
    <script>
        const p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('OK1');
                // reject('error');
            }, 2000);
            console.log(111);
        })

        // 如果不catch ，p resolve中的错误，那么会在p1的reject中捕捉到这个异常
        // 如果catch了p resolve中的错误，那么会在catch中捕捉到这个异常；同时p1 resolve也会执行，res的值为undefined;
        const p1 = p.then(value => {
            console.log(222, value);
            throw new Error('error');
            return Promise.resolve('OK2');
        }, err => {
            console.log('err1', err);
        }).catch(err => {
            console.log('catch1', err);
        })
        
        p1.then(res => {
            console.log(444, res);
        }, err => {
            console.log('err2', err);
        }).catch(err => {
            console.log('catch2', err);
        });

        console.log(333);

        Promise.all([Promise.resolve(2), Promise.reject(3)]).then(res => {
            console.log('all res', res);
        }, err => {
            console.log('all err', err);
        });
        
        Promise.race([Promise.reject(1), Promise.resolve(2), Promise.reject(3)]).then(res => {
            console.log('race res', res);
        }, err => {
            console.log('race err', err);
        });

    </script>
</body>
</html>